export const API_URL = "http://eatmeapi.herokuapp.com/api";

// Begin LocalStorage

export const SELECTED_ESTABLISHMENT_ID = "selectedEstablishmentId";
export const SELECTED_DISHES = "selectedDishes";
export const ORDER_QUANTITY = "orderQuantity";
export const ACCOUNT_ID = "accountId";

// End localStorage

// Begin Reducers

export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_CATEGORIES_FAILURE = "GET_CATEGORIES_FAILURE";

export const GET_CUISINES = "GET_CUISINES";
export const GET_CUISINES_SUCCESS = "GET_CUISINES_SUCCESS";
export const GET_CUISINES_FAILURE = "GET_CUISINES_FAILURE";

export const GET_ESTABLISHMENTS = "GET_ESTABLISHMENTS";
export const GET_ESTABLISHMENTS_SUCCESS = "GET_ESTABLISHMENTS_SUCCESS";
export const GET_ESTABLISHMENTS_FAILURE = "GET_ESTABLISHMENTS_FAILURE";

export const GET_ESTABLISHMENTS_CATEGORIES = "GET_ESTABLISHMENTS_CATEGORIES";
export const GET_ESTABLISHMENTS_CATEGORIES_SUCCESS = "GET_ESTABLISHMENTS_CATEGORIES_SUCCESS";
export const GET_ESTABLISHMENTS_CATEGORIES_FAILURE = "GET_ESTABLISHMENTS_CATEGORIES_FAILURE";

export const GET_ACCOUNTS = "GET_ACCOUNTS";
export const GET_ACCOUNTS_SUCCESS = "GET_ACCOUNTS_SUCCESS";
export const GET_ACCOUNTS_FAILURE = "GET_ACCOUNTS_FAILURE";

export const GET_FAST_CUSTOMERS = "GET_FAST_CUSTOMERS";
export const GET_FAST_CUSTOMERS_SUCCESS = "GET_FAST_CUSTOMERS_SUCCESS";
export const GET_FAST_CUSTOMERS_FAILURE = "GET_FAST_CUSTOMERS_FAILURE";

export const GET_DISHES = "GET_DISHES";
export const GET_DISHES_SUCCESS = "GET_DISHES_SUCCESS";
export const GET_DISHES_FAILURE = "GET_DISHES_FAILURE";

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_FAILURE = "GET_ORDERS_FAILURE";

export const POST_ORDER = "POST_ORDER";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILURE = "POST_ORDER_FAILURE";

export const SEARCH_CHANGED = "SEARCH_CHANGED";
export const SEARCH_TYPING_START = "SEARCH_TYPING_START";
export const SEARCH_TYPING_END = "SEARCH_TYPING_END";
export const SEARCH_CLEARED = "SEARCH_CLEARED";

export const FILTER_CATEGORIES_CHECKED = "FILTER_CATEGORIES_CHECKED";
export const FILTER_CATEGORIES_UNCHECKED_ALL = "FILTER_CATEGORIES_UNCHECKED_ALL";

export const FILTER_CUISINES_CHECKED = "FILTER_CUISINES_CHECKED";
export const FILTER_CUISINES_UNCHECKED_ALL = "FILTER_CUISINES_UNCHECKED_ALL";

export const SET_ORDER_DISHES = "SET_ORDER_DISHES";
export const SET_ORDER_QUANTITY = "SET_ORDER_QUANTITY";

// End Reducers
