# Generated by Django 3.0.2 on 2020-01-18 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null='True', verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Кухня',
                'verbose_name_plural': 'Кухні',
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Назва')),
                ('image', models.ImageField(upload_to='foodImages', verbose_name='Зображення')),
                ('price', models.FloatField(default=0, verbose_name='Ціна')),
                ('weight', models.FloatField(default=0, verbose_name='Вага')),
                ('composition', models.TextField(blank=True, null=True, verbose_name='Склад')),
                ('calorie', models.FloatField(default=0, verbose_name='Калорії')),
                ('state', models.CharField(choices=[('available', 'В наявності'), ('ends', 'Закінчується'), ('absent', 'Відсутня')], default='available', max_length=302, verbose_name='Стан')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.Category', verbose_name='Категорія')),
                ('cuisine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.Cuisine', verbose_name='Кухня')),
            ],
            options={
                'verbose_name': 'Страв',
                'verbose_name_plural': 'Страви',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Назва')),
                ('image', models.ImageField(upload_to='institutionImages', verbose_name='Зображення')),
                ('about', models.TextField(verbose_name='Про заклад')),
                ('timeFrom', models.TimeField(verbose_name='От')),
                ('timeBefore', models.TimeField(verbose_name='До')),
                ('position', models.CharField(max_length=100, verbose_name='Адреса')),
                ('cuisine', models.ManyToManyField(to='menu.Cuisine', verbose_name='Кухня')),
                ('menu', models.ManyToManyField(to='menu.Dish', verbose_name='Меню')),
            ],
            options={
                'verbose_name': 'Заклад',
                'verbose_name_plural': 'Заклади',
            },
        ),
    ]
