# Generated by Django 3.0.2 on 2020-01-19 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='foodImages', verbose_name='Зображення'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='institutionImages', verbose_name='Зображення'),
        ),
    ]
