# Generated by Django 3.0.2 on 2020-01-19 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200119_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='phone',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='Мобільний телефон'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='about',
            field=models.TextField(blank=True, null=True, verbose_name='Про заклад'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='cuisine',
            field=models.ManyToManyField(blank=True, null=True, to='menu.Cuisine', verbose_name='Кухня'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='menu',
            field=models.ManyToManyField(blank=True, null=True, to='menu.Dish', verbose_name='Меню'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Адреса'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='timeBefore',
            field=models.TimeField(blank=True, null=True, verbose_name='До'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='timeFrom',
            field=models.TimeField(blank=True, null=True, verbose_name='От'),
        ),
    ]
