# Generated by Django 3.0.2 on 2020-01-22 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, null=True, verbose_name="Ім'я")),
                ('surname', models.CharField(blank=True, max_length=50, null=True, verbose_name='Прізвище')),
                ('customerPhone', models.CharField(blank=True, default='', max_length=12, verbose_name='Номер телефону')),
                ('paymentMethod', models.CharField(blank=True, choices=[('cash', "Оплата готівкова кур'єру"), ('cashless', "Оплата безготівкова кур'єру"), ('online', 'Оплата онлайн')], default='online', max_length=50, verbose_name='Спосіб оплати')),
                ('orderTime', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата замовлення')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплата')),
                ('orderList', models.ManyToManyField(blank=True, to='menu.Dish', verbose_name='Зміст замовлення')),
            ],
            options={
                'verbose_name': 'Замовлення',
                'verbose_name_plural': 'Замовлення',
            },
        ),
    ]
