# Generated by Django 3.0.2 on 2020-01-19 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Замовлення', 'verbose_name_plural': 'Замовлення'},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='name',
            new_name='full_name',
        ),
    ]
