# Generated by Django 3.0.2 on 2020-01-23 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderSum',
            field=models.FloatField(default=0, verbose_name='Сума замовлення'),
        ),
    ]
