# Generated by Django 3.0.2 on 2020-01-23 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0002_order_ordersum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderList',
        ),
        migrations.AddField(
            model_name='order',
            name='orderList',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='menu.Dish', verbose_name='Зміст замовлення'),
        ),
    ]
