# Generated by Django 3.0.2 on 2020-04-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20200418_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderDetail',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Подробиці'),
        ),
    ]
