# Generated by Django 3.0.2 on 2020-01-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200119_0942'),
        ('order', '0002_auto_20200119_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='full_name',
            new_name='fullName',
        ),
        migrations.AddField(
            model_name='order',
            name='orderList',
            field=models.ManyToManyField(to='menu.Dish', verbose_name='Зміст замовлення'),
        ),
        migrations.AddField(
            model_name='order',
            name='orderTime',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата замовлення'),
        ),
        migrations.AddField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=False, verbose_name='Оплата'),
        ),
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('cash', "Оплата готівкова кур'єру"), ('cashless', "Оплата безготівкова кур'єру"), ('online', 'Оплата онлайн')], default='online', max_length=50, verbose_name='Спосіб оплати'),
        ),
    ]
