# Generated by Django 3.0.2 on 2020-04-24 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_orderdetail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderList',
        ),
        migrations.AddField(
            model_name='order',
            name='orderList',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Список замовлених страв'),
        ),
    ]
