# Generated by Django 3.0.2 on 2020-04-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_auto_20200418_1228'),
        ('order', '0004_auto_20200424_1020'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='orderListTextField',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Список замовлених страва'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='orderList',
        ),
        migrations.AddField(
            model_name='order',
            name='orderList',
            field=models.ManyToManyField(blank=True, to='menu.Dish', verbose_name='Зміст замовлення'),
        ),
    ]
