# Generated by Django 3.0.2 on 2020-01-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0008_auto_20200123_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderList',
        ),
        migrations.AddField(
            model_name='order',
            name='orderList',
            field=models.ManyToManyField(blank=True, to='menu.Dish', verbose_name='Зміст замовлення'),
        ),
    ]
