# Generated by Django 3.0.2 on 2020-01-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('order', '0009_auto_20200123_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='orderSum',
        ),
        migrations.AlterField(
            model_name='order',
            name='orderList',
            field=models.ManyToManyField(to='menu.Dish', verbose_name='Зміст замовлення'),
        ),
    ]
